# Generated by Django 5.0.10 on 2025-01-19 05:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNombreTalla', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'Talla',
            },
        ),
        migrations.CreateModel(
            name='ProductUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.productcategory')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.season')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talla')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cRutaImagen', models.ImageField(upload_to='photos/%Y/%m/')),
                ('bEsActivo', models.BooleanField(blank=True, null=True)),
                ('dFechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productunidad')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'ImagenesProductos',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Descuento en porcentaje (Ej: 20 para 20%)', max_digits=5)),
                ('code', models.CharField(blank=True, help_text='Código de descuento (opcional)', max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='promotions', to='product.productunidad')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
    ]
