# Generated by Django 5.0.10 on 2025-01-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunidad',
            name='promociones',
            field=models.ManyToManyField(blank=True, related_name='product_unidades', to='product.promotion'),
        ),
    ]
