# Generated by Django 5.0.10 on 2025-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productunidad_promociones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunidad',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
