# Generated by Django 5.0.10 on 2025-01-19 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productunidad_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunidad',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
