# Generated by Django 5.0.10 on 2025-01-19 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productunidad_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='dFechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
