# Generated by Django 5.0.10 on 2025-01-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_imagenproducto_dfechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunidad',
            name='promociones',
        ),
    ]
