# Generated by Django 5.0.10 on 2025-01-19 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0006_remove_productunidad_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunidad',
            name='promotions',
            field=models.ManyToManyField(related_name='associated_products', to='product.promotion', verbose_name='Promociones asociadas'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.productcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.season', verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='productunidad',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talla', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='associated_promotions', to='product.productunidad'),
        ),
    ]
