# Generated by Django 5.0.10 on 2025-01-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productunidad_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunidad',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='associated_products', to='product.promotion', verbose_name='Promociones asociadas'),
        ),
    ]
