# Generated by Django 5.0.10 on 2025-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productunidad_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunidad',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
    ]
