# Generated by Django 5.0.10 on 2025-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productunidad_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunidad',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (RGB)'),
        ),
    ]
