# Generated by Django 5.0.10 on 2025-02-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productunidad_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunidad',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.talla', verbose_name='Talla'),
        ),
    ]
