# Generated by Django 5.0.10 on 2025-02-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_imagenproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productunidad'),
        ),
    ]
