# Generated by Django 5.0.10 on 2025-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_imagenproducto_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={},
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='dFechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='imagenproducto',
            table=None,
        ),
    ]
