# Generated by Django 5.0.10 on 2025-03-01 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='dFechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='imagenproducto',
            table='ImagenesProductos',
        ),
    ]
