# Generated by Django 5.0.10 on 2025-03-03 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad de esta talla')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='product.productunidad')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talla')),
            ],
        ),
    ]
