# Generated by Django 5.0.10 on 2025-03-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_producttalla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTalla',
        ),
    ]
