# Generated by Django 5.0.10 on 2025-03-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_producttalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunidad',
            name='talla',
        ),
    ]
