# Generated by Django 5.0.10 on 2025-03-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_productunidad_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTallaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talla_stock', to='product.productunidad')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.talla')),
            ],
            options={
                'unique_together': {('product', 'talla')},
            },
        ),
    ]
