# Generated by Django 5.0.10 on 2025-03-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_producttallastock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunidad',
            name='color',
        ),
        migrations.CreateModel(
            name='ProductColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stock', to='product.productunidad')),
            ],
            options={
                'unique_together': {('product', 'color')},
            },
        ),
    ]
