# Generated by Django 5.0.10 on 2025-03-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_productunidad_color_productcolorstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
    ]
