# Generated by Django 5.0.10 on 2025-03-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_promotion_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanerInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=255)),
                ('imagen_banner_base64', models.TextField()),
                ('imagen_extra_base64', models.TextField()),
            ],
        ),
    ]
