# Generated by Django 5.0.10 on 2025-03-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_banerinicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banerinicio',
            name='imagen_banner_base64',
        ),
        migrations.RemoveField(
            model_name='banerinicio',
            name='imagen_extra_base64',
        ),
        migrations.AddField(
            model_name='banerinicio',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='banerinicio',
            name='imagen_extra',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
