# Generated by Django 5.0.10 on 2025-03-14 03:01

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_banerinicio_imagen_banner_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banerinicio',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='banerinicio',
            name='imagen_extra',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.models.upload_to),
        ),
    ]
