# Generated by Django 5.0.10 on 2025-03-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_banerinicio_imagen_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTendencia', models.CharField(max_length=255)),
                ('titleTendencia', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productunidad')),
            ],
        ),
    ]
