# Generated by Django 5.0.10 on 2025-03-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_carruselproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='money',
            field=models.BooleanField(default=False),
        ),
    ]
