# Generated by Django 5.0.10 on 2025-04-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_promotion_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha utilizado esta promoción.'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Número de veces que puede ser usado el descuento. Deja vacío para sin límite.', null=True),
        ),
    ]
