# Generated by Django 5.0.10 on 2025-04-29 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_promotion_usage_count_promotion_usage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de promoción',
                'verbose_name_plural': 'Usos de promociones',
                'unique_together': {('user', 'promotion')},
            },
        ),
    ]
