# Generated by Django 5.0.10 on 2025-04-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_promotionusage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together=set(),
        ),
    ]
