# Generated by Django 5.0.10 on 2025-04-29 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_promotionusage_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together={('user', 'promotion')},
        ),
    ]
