# Generated by Django 5.0.10 on 2025-04-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_promotionusage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together=set(),
        ),
    ]
