"""
Django settings for projectApi project.

Generated by 'django-admin startproject' using Django 5.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta


env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(env('DATABASE_URL'))


# ✅ Agrega esto
API_BASE_URL = env("API_BASE_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

#para google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')








# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APP=['apps.user']
ECOMMERCE_APP=['apps.category','apps.product', 'apps.cart', 'apps.orders','apps.shipping','apps.payment']
THIRD_PARTY_APP = [
    'corsheaders',
    'rest_framework',
    'djoser',
    'social_media',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 'django.contrib.sites',
    'ckeditor',
    'ckeditor_uploader',
    'social_django',
    'djoser.social',
    'dj_rest_auth',
    'rest_framework.authtoken',
    'networkx',
    'whitenoise',
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APP + ECOMMERCE_APP + THIRD_PARTY_APP

CKEDITOR_CONFIGS = {
    'default':{
        'toolbar' : 'full',
        'autoParagraph' : False
    }
}

CKEDITOR_UPLOAD_PATH = "/media/"




MIDDLEWARE = [
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'corsheaders.middleware.CorsMiddleware', #PARA LA AUTENTIFICACIÓN
    # 'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'build', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True


#CAMBIAR POR EL NOMBRE DE TU DOMINIO
CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:3000',
]

#sitios que pueden comunicarse con tu página
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:3000',
]

# CORS_ALLOW_CREDENTIALS = True 

# SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']
# SOCIALACCOUNT_STATE = False


# SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {'access_type': 'offline'}

CSRF_COOKIE_HTTPONLY = False  # Asegura que JS pueda leer la cookie
CSRF_COOKIE_SAMESITE = "Lax"  # Permitir envío de CSRF desde el mismo sitio

# # Evita la verificación de `state`
# SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
# SOCIAL_AUTH_SANITIZE_REDIRECTS = False
# SOCIAL_AUTH_STATELESS = True
# SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']
# Password validation

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]



# CORS_ALLOW_CREDENTIALS = True  # ✅ Permitir cookies seguras en CORS
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:8000",  # ✅ Especifica los dominios permitidos
#     "http://localhost:8000",
# ]
# CSRF_COOKIE_SECURE = True  # ✅ Asegurar que la cookie solo se envíe en HTTPS
# SESSION_COOKIE_SECURE = True  # ✅ Lo mismo para sesiones
# CSRF_COOKIE_HTTPONLY = True  # 🔥 Protección extra contra JavaScript
# CSRF_COOKIE_SAMESITE = "Lax"  # ✅ Protección CSRF básica
# SESSION_COOKIE_SAMESITE = "Lax"  # ✅ Lo mismo para sesiones


# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Lima'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



STATIC_URL = '/static/'
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'withenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'build', 'static')  # Ruta a tu carpeta de archivos estáticos
]

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    # 'social_core.pipeline.user.activate_user',
)

REST_USE_JWT = True  # Habilitar JWT en dj-rest-auth

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticatedOrReadOnly',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
#     'PAGE_SIZE': 50 
# }

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50 
}


#PARA HACER LOGIN CORRECTAMENTE
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)




# Configurar los permisos de Google para obtener el perfil e imagen
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'  # Necesario para obtener la imagen
]

# Configurar qué datos extra se almacenarán, incluyendo la imagen de perfil
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['picture']



#para que la página se guarde en el navegador

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer', ),  # Cambiado de "JWT" a "Bearer"
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3000),  # Máximo 30-60 min por seguridad
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Se mantiene en 30 días
    'ROTATE_REFRESH_TOKENS': True,  # Se renueva el refresh token en cada solicitud
    'BLACKLIST_AFTER_ROTATION': True,  # El refresh token anterior se invalida
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'COOKIE_SECURE': True,  # Solo en HTTPS (para producción)
    'COOKIE_HTTPONLY': True,  # Evita acceso con JavaScript (más seguro)
    'COOKIE_SAMESITE': 'Lax',  # Para evitar ataques CSRF
}


DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'TOKEN_MODEL': None,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': True, #para que se logeen despues de confirmar su correo
    'SET_USERNAME_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': [
        'http://localhost:8000/google', 
        'http://localhost:8000/facebook'
        ],
    'SERIALIZERS': {
        'user_create': 'apps.user.serializers.UserCreateSerializer',
        'user': 'apps.user.serializers.UserCreateSerializer',
        'current_user': 'apps.user.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
}

AUTH_USER_MODEL = 'user.UserAccount'

# PARA LOS PAGO
BT_ENVIRONMENT = os.environ.get('BT_ENVIRONMENT')
BT_MERCHANT_ID = os.environ.get('BT_MERCHANT_ID')
BT_PUBLIC_KEY = os.environ.get('BT_PUBLIC_KEY')
BT_PRIVATE_KEY = os.environ.get('BT_PRIVATE_KEY')



#CONFIGURAR EL CORREO ELECTRÓNICO
#DESIGNAR EL EMAIL BACKEND
#para enviar correos


# Configuración del correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/user-logated/'
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/user-logated/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
