# Generated by Django 5.0.10 on 2025-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_color_cartitem_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='talla',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='numbertalla',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='numbertalla'),
        ),
    ]
