# Generated by Django 5.0.10 on 2025-03-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_talla_cartitem_numbertalla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='numbertalla',
            new_name='talla',
        ),
    ]
